apiVersion: v1
kind: Service
metadata:
  name: broken-orders-service
  namespace: shopsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orders-api-wrong-label
  ports:
    - name: http
      port: 8080
      targetPort: http
