apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-db-secret
  namespace: shopsphere
  labels:
    app.kubernetes.io/name: shopsphere
    app.kubernetes.io/part-of: shopsphere
type: Opaque
stringData:
  POSTGRES_USER: shopsphere_user
  POSTGRES_PASSWORD: shopsphere_password_123
  POSTGRES_DB: shopsphere
